### ISSUE TITLE
miss file /data/chembl_voc.txt

### ISSUE THREAD

**Issue by ChengchengGutenTag** [XuhanLiu/DrugEx#16]
Hi, great work! I may want to try it on my datasets. But it returned the error that "FileNotFoundError: [Errno 2] No such file or directory: 'data/chembl_voc.txt'." Could you please enclose this file? Thank you very much in advance!

**Comment by martin-sicho** [comment]
Hi @annie20220104, I am not sure which model you are trying to train/use, but you can find the files in our fork [here](https://github.com/CDDLeiden/DrugEx), which is still work in progress, but adds command line interface and other goodies in the future :)

EDIT: Now I see the files are actually here as well (just the name is maybe different?): https://github.com/XuhanLiu/DrugEx/blob/master/data/voc_smiles.txt

**Comment by ChengchengGutenTag** [comment]
Thank you very much @martin-sicho for your kind and quick reply! It seems that somehow the file names in my local folder has a different name from the original names. I can run the code with no problems now. Many thanks!

**Comment by XuhanLiu** [comment]
Thanks for reminding me of this bugs. I have changed it from "chembl_voc.txt" to "voc_smiles.txt".
