### ISSUE TITLE
No utils.canonicalize_list in Drug_ex v2.0

### ISSUE THREAD

**Issue by ForeverForL** [XuhanLiu/DrugEx#22]
Thanks for sharing such an interesting tool . But I got some problems when running the project.
In Drug_ex v2.0 ->rlearner.py ->class Evolve->def fit()
![image](https://user-images.githubusercontent.com/82694461/222703784-fe11df09-fd53-4b10-a602-70857494c2a9.png)
but there's no 'canonicalize_list' function in utils
Hope you can reply to me.

**Comment by martin-sicho** [comment]
Hi @ForeverForL,

thanks for the interest in the project! We now have a more bug-free and more convenient [package](https://github.com/CDDLeiden/DrugEx) to use. You will find the v2 model implemented there as well and it also has a [dedicated tutorial](https://github.com/CDDLeiden/DrugEx/blob/master/tutorial/Sequence-RNN.ipynb).

**Comment by ForeverForL** [comment]
Thank you for your early reply! I would close the comment!
